version: '3'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn things_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 4

    volumes:
      - .:/code
    ports:
      - "8000:8000"
#     depends_on:
#       - db
#   db:
#     image: postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_DB=${DB_NAME}
#       - POSTGRES_USER=${USER_NAME}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
# volumes:
#     postgres_data:
